// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: src/api/shortener.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LongURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lurl string `protobuf:"bytes,1,opt,name=lurl,proto3" json:"lurl,omitempty"`
}

func (x *LongURL) Reset() {
	*x = LongURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_shortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongURL) ProtoMessage() {}

func (x *LongURL) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_shortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongURL.ProtoReflect.Descriptor instead.
func (*LongURL) Descriptor() ([]byte, []int) {
	return file_src_api_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *LongURL) GetLurl() string {
	if x != nil {
		return x.Lurl
	}
	return ""
}

type ShortURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Surl string `protobuf:"bytes,1,opt,name=surl,proto3" json:"surl,omitempty"`
}

func (x *ShortURL) Reset() {
	*x = ShortURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_shortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURL) ProtoMessage() {}

func (x *ShortURL) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_shortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURL.ProtoReflect.Descriptor instead.
func (*ShortURL) Descriptor() ([]byte, []int) {
	return file_src_api_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortURL) GetSurl() string {
	if x != nil {
		return x.Surl
	}
	return ""
}

var File_src_api_shortener_proto protoreflect.FileDescriptor

var file_src_api_shortener_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x07, 0x4c, 0x6f, 0x6e,
	0x67, 0x55, 0x52, 0x4c, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6c, 0x75, 0x72, 0x6c, 0x22, 0x1e, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x55, 0x52, 0x4c, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x75, 0x72, 0x6c, 0x32, 0x56, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x6e, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65,
	0x77, 0x12, 0x08, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x52, 0x4c, 0x1a, 0x09, 0x2e, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41,
	0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x64, 0x12, 0x09, 0x2e, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x55, 0x52, 0x4c, 0x1a, 0x08, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x52, 0x4c, 0x22, 0x00,
	0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41,
	0x70, 0x70, 0x43, 0x72, 0x61, 0x73, 0x68, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x2f, 0x67,
	0x6f, 0x2d, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_api_shortener_proto_rawDescOnce sync.Once
	file_src_api_shortener_proto_rawDescData = file_src_api_shortener_proto_rawDesc
)

func file_src_api_shortener_proto_rawDescGZIP() []byte {
	file_src_api_shortener_proto_rawDescOnce.Do(func() {
		file_src_api_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_api_shortener_proto_rawDescData)
	})
	return file_src_api_shortener_proto_rawDescData
}

var file_src_api_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_api_shortener_proto_goTypes = []interface{}{
	(*LongURL)(nil),  // 0: LongURL
	(*ShortURL)(nil), // 1: ShortURL
}
var file_src_api_shortener_proto_depIdxs = []int32{
	0, // 0: Shortner.CreateNew:input_type -> LongURL
	1, // 1: Shortner.GetAssociated:input_type -> ShortURL
	1, // 2: Shortner.CreateNew:output_type -> ShortURL
	0, // 3: Shortner.GetAssociated:output_type -> LongURL
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_api_shortener_proto_init() }
func file_src_api_shortener_proto_init() {
	if File_src_api_shortener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_api_shortener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_shortener_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_api_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_api_shortener_proto_goTypes,
		DependencyIndexes: file_src_api_shortener_proto_depIdxs,
		MessageInfos:      file_src_api_shortener_proto_msgTypes,
	}.Build()
	File_src_api_shortener_proto = out.File
	file_src_api_shortener_proto_rawDesc = nil
	file_src_api_shortener_proto_goTypes = nil
	file_src_api_shortener_proto_depIdxs = nil
}
